// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroPedidos.Dal;

namespace RegistroPedidos.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20210620030118_migration_Inicial")]
    partial class migration_Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("RegistroPedidos.Models.Ordenes", b =>
                {
                    b.Property<int>("OrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<int>("SuplidorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrdenId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("RegistroPedidos.Models.OrdenesDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Costo")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrdenId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId");

                    b.ToTable("OrdenesDetalle");
                });

            modelBuilder.Entity("RegistroPedidos.Models.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Costo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Inventario")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Costo = 50m,
                            Descripcion = "Pan",
                            Inventario = 87m
                        },
                        new
                        {
                            ProductoId = 2,
                            Costo = 179m,
                            Descripcion = "Jugo de Naranja",
                            Inventario = 53m
                        },
                        new
                        {
                            ProductoId = 3,
                            Costo = 50m,
                            Descripcion = "Coca Cola",
                            Inventario = 97m
                        },
                        new
                        {
                            ProductoId = 4,
                            Costo = 42m,
                            Descripcion = "Chocolate Cortes",
                            Inventario = 75m
                        },
                        new
                        {
                            ProductoId = 5,
                            Costo = 317m,
                            Descripcion = "Arroz Campo",
                            Inventario = 57m
                        });
                });

            modelBuilder.Entity("RegistroPedidos.Models.Suplidores", b =>
                {
                    b.Property<int>("SuplidorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("SuplidorId");

                    b.ToTable("Suplidores");

                    b.HasData(
                        new
                        {
                            SuplidorId = 1,
                            Nombres = "Yoma"
                        },
                        new
                        {
                            SuplidorId = 2,
                            Nombres = "Rica"
                        },
                        new
                        {
                            SuplidorId = 3,
                            Nombres = "La Sirena"
                        },
                        new
                        {
                            SuplidorId = 4,
                            Nombres = "Porvenir"
                        },
                        new
                        {
                            SuplidorId = 5,
                            Nombres = "Palmares"
                        });
                });

            modelBuilder.Entity("RegistroPedidos.Models.OrdenesDetalle", b =>
                {
                    b.HasOne("RegistroPedidos.Models.Ordenes", null)
                        .WithMany("OrdenesDetalle")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegistroPedidos.Models.Ordenes", b =>
                {
                    b.Navigation("OrdenesDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
